### ISSUE TITLE
Null pointer exception in Input Ticket Audit

### ISSUE THREAD

**Issue by marco44** [matthewtckr/pdi-zendesk-plugin#28]
Hi and thanks for writing this plugin.

I'm having this error:

```
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - ERROR (version 7.1.0.6-73, build 1 from 2017-11-10 10.59.25 by marc) : Unexpected error
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - ERROR (version 7.1.0.6-73, build 1 from 2017-11-10 10.59.25 by marc) : java.lang.NullPointerException
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.step.BaseStep.handlePutError(BaseStep.java:1669)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.step.BaseStep.access$300(BaseStep.java:147)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.step.BaseStep$DefaultRowHandler.putError(BaseStep.java:4189)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.step.BaseStep.putError(BaseStep.java:1650)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.steps.zendesk.ZendeskInputTicketAudit.processRow(ZendeskInputTicketAudit.java:121)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/12/06 14:16:08 - Zendesk Input Ticket Audits.0 - 	at java.lang.Thread.run(Thread.java:748)
```

Looking at the code, if I understand correctly, 

```
     if ( 404 == zre.getStatusCode() ) {
        putError( getInputRowMeta(), row, 1L, zre.toString(),
          getInputRowMeta().getValueMeta( ticketIdFieldIndex ).getName(), zre.getStatusText() );
```

I get a 404 from the server. But I get a null pointer exception instead of the ticketID in the error message. No idea why... so I'm stuck.

Please tell me what I can provide…

Regards.

**Comment by matthewtckr** [comment]
Thanks for the stack trace.  It sounds like you may not have an "Error handling" hop in your transformation, which may be causing the NullPointerException when it tries to find that hop to write the error row.

If that doesn't resolve the issue, can you send me an email (mtucker@pentaho.com) with the attachment, so I review it? Be sure to strip any username/password settings from the file before sending.

Let me know if that helps.

**Comment by marco44** [comment]
It's exactly the problem… I had no error step. Thanks a lot.

**Comment by marco44** [comment]
Sorry I'm a beginner, but I have almost 10% of these records in error. I see in the example in the wiki  a «remove invalid ticket ids» step, is this linked ?

**Comment by matthewtckr** [comment]
The example screenshot is from my own PDI transformation that I run daily.  In my case, there are some tickets that for whatever reason exist only in the Incremental Tickets API, but not in any other API endpoint.  I've never gotten a good answer as to why this happens, unfortunately.

When I come across those specific Ticket IDs that I want to avoid, I just add those Ticket IDs into a Data Grid step, and have a filter to prevent me from asking for Ticket Audit records for those Ticket IDs.

If you're getting 10% of your tickets responding with a 404 error, do you see them in the Zendesk UI when you're logged in as an admin? If you do see them, you might need to raise a ticket with Zendesk Support asking why the API does not return the ticket information.  If you do not see them in the Zendesk UI, you may want to ignore, or actively filter them like in my example.

**Comment by marco44** [comment]
Ok, that's much clearer, thanks.
Another question (I hope it's the last one), I see in the example that you are using the table output. I don't understand how this doesn't produce duplicates, if a ticket has been updated ? I would, instinctively, have used an insert/update step...

**Comment by matthewtckr** [comment]
I send everything into a truncated staging table, and then have another SQL query that handles the insert/update into the final table after that transformation.

This helps to avoid any PDI<->Database latency as Insert/Update typically has to do a round-trip for each record.

**Comment by marco44** [comment]
Ok, we dug a bit into the zendesk UI with a colleague which is more proficient than me. It seems that these are delete tickets. As we only have the latest deleted tickets in the GUI, we can only check for those, but there is a 100% match with recent deleted tickets. So the API returns even ids of deleted tickets, which cannot be retrieved. And they confirm me that they did a lot of tests a while a go, and the big amount of deleted tickets and their range is consistent with that.
