### ISSUE TITLE
Zendesk returns userids that are no longer available

### ISSUE THREAD

**Issue by marco44** [matthewtckr/pdi-zendesk-plugin#29]
Hi,

I'm trying to retrieve the list of users this time… and I also get a 404 for some ids. But there is no code to catch this error, and no error stream for the Zendesk Input Users step, so my transformation dies.

I'm trying to add this to the plugin, but as I haven't been programming in java for a while… :)

**Comment by matthewtckr** [comment]
Resolved in v1.2.2.  Thanks for the fix!
