### ISSUE TITLE
rate limiting from zendesk

### ISSUE THREAD

**Issue by marco44** [matthewtckr/pdi-zendesk-plugin#31]
I hit another problem: I am often killed by Zendesk's rate limiting. From what I see, this exception isn't caught by the current code. Do you confirm ? (I'll work on a PR)

**Comment by matthewtckr** [comment]
Hi Marco, this has been incorporated into [v1.2.2](https://github.com/matthewtckr/pdi-zendesk-plugin/releases/tag/pdi-zendesk-plugin-1.2.2), but it will be a few days before it gets into the PDI Marketplace.

Thanks for adding this awesome feature!

**Comment by marco44** [comment]
Thank you for having written this plugin in the first place :)
