### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by yaskovvlad** [matthewtckr/pdi-zendesk-plugin#34]
Hi Matthew, I've installed your plugin but have some problem with getting commends and other ticket's attributes via pdi. Can you pls commit your pdi examples? Many thanks!

**Comment by matthewtckr** [comment]
Hi @yaskovvlad,

I've [added a sample to the Wiki](https://github.com/matthewtckr/pdi-zendesk-plugin/wiki/Examples) for download.

Regards
