### ISSUE TITLE
Need data from getTicketField

### ISSUE THREAD

**Issue by marco44** [matthewtckr/pdi-zendesk-plugin#37]
Hi,

Our users store important metadata from https://peopledoc.zendesk.com/api/v2/ticket_fields/{id}.json (some metadata in tags). Is there a way to retrieve them ?

I don't see one implemented right now, does it means extending "Input Ticket Fields"… if so, is there an easy way to do it ?

**Comment by matthewtckr** [comment]
Hey @marco44,

Yes, the Input Ticket Fields step is used to return data from the `https://<subdomain>.zendesk.com/api/v2/ticket_fields.json` API endpoint.  The step was developed only to return the fields I needed for my project, so there are additional fields that could be returned by adding them into the various step classes.

**Comment by matthewtckr** [comment]
I'm currently working in [this branch](https://github.com/matthewtckr/pdi-zendesk-plugin/tree/ticketfields) to change how the Ticket Fields step is written, so it should make it easier to add more fields in the future.  There's still quite a bit of work to be done, though.

**Comment by matthewtckr** [comment]
Created PR #41

**Comment by matthewtckr** [comment]
Released in [v1.3.1](https://github.com/matthewtckr/pdi-zendesk-plugin/releases/tag/pdi-zendesk-plugin-1.3.1)

**Comment by marco44** [comment]
Great ! I'm currently in holiday, but I'll give it a go as soon as I'm back :)
