### ISSUE TITLE
Feature to filter deleted tickets from get input incrementally step

### ISSUE THREAD

**Issue by lweijl** [matthewtckr/pdi-zendesk-plugin#43]
Hi,

I have a request. Within our company we have a kettle project where we use your plugin. Recently someone has done some testing against Zendesk and has deleted some tickets. Since then jobs are failing.
I think that I have managed to track it down to the zendesk incremental input step. Within ZendeskInputIncremental.java on line 95, the getTicketsIncrementally method is called. I believe this method corresponds to the following API call of Zendesk (https://developer.zendesk.com/rest_api/docs/core/incremental_export#start-time). Within that webpage it states that tickets that are deleted can be filtered using “status”: “deleted”.

Snippet from the website
> Excluding deleted tickets
> Starting on October 16, 2016, user-provided information in deleted tickets is scrubbed 30 days after deletion. Reporting on deleted tickets remains intact because the ticket record still exists. However, user-provided information (as opposed to system-provided information) is scrubbed with an X for text fields, a 0 for numeric fields, or nothing for fields that didn't have a value. You can exclude these tickets by filtering out any tickets with a "status": "deleted" value.

It seems that the zendesk incremental input step fetches all ticket ids, and does not filter out deleted tickets. Could you look into this maybe and add such a feature?

**Comment by matthewtckr** [comment]
I'm hesitant to filter these within the step, but we could add an output field for `status`, where you can then use a "Filter Rows" step if you'd like to remove those specific tickets.

**Comment by matthewtckr** [comment]
Merged #44, will work to release an update soon

**Comment by matthewtckr** [comment]
Released in [v1.3.1](https://github.com/matthewtckr/pdi-zendesk-plugin/releases/tag/pdi-zendesk-plugin-1.3.1)
